-- AlterTable
ALTER TABLE "Planet" ALTER COLUMN "rotation_period" DROP NOT NULL,
ALTER COLUMN "orbital_period" DROP NOT NULL,
ALTER COLUMN "gravity" DROP NOT NULL,
ALTER COLUMN "surface_water" DROP NOT NULL,
ALTER COLUMN "url" DROP NOT NULL,
ALTER COLUMN "created" DROP NOT NULL,
ALTER COLUMN "edited" DROP NOT NULL;
